mod diff;
mod diff_ctx;
mod diff_decide;
mod diff_fill_skip;
mod diff_object;
mod diff_plan;
mod diff_prepare;
mod path_cache;
pub mod filter_migrations;
mod git_scope;
mod scenario;
mod scenario_apply;
mod scenario_resolve;
pub mod scope;
mod scope_build;
pub mod transitions;

pub use diff::{compute_diff, compute_diff_into};
pub use git_scope::git_hot_scope_json;
pub use scenario::{CounterKind, PlanScenario};
pub use scenario_apply::apply_scenario;
pub use scenario_resolve::{resolve_plan_scenario, ScenarioInput};
pub use path_cache::{rebuild_object_path_cache, rebuild_path_caches};
pub use transitions::rebuild_transition_path_cache;
